/**
 * This file is auto-generated by the vite-plugin-topic-titles-manifest plugin.
 * Do not edit manually. Run `bun run build` or `bun run dev` to regenerate.
 *
 * Maps topic slugs to their actual titles extracted from markdown files.
 */
export const TOPIC_TITLES: Record<string, string> = {
  'adding-objects': 'Adding Objects',
  'ai-chat': 'Chat',
  'ai-edits': 'Edits',
  'ai-patch-to-app': 'Patch to App',
  'audio-chaining': 'Audio Chaining',
  'audio-reactivity': 'Audio Reactivity',
  'browse-samples': 'Samples',
  'canvas-interaction': 'Canvas Interaction',
  'clock-api': 'Clock API',
  'connecting-objects': 'Connecting Objects',
  'data-storage': 'Data Storage',
  'data-types': 'Data Types',
  demos: 'Demos',
  'enabling-ai': 'Enabling AI',
  'glsl-imports': 'GLSL Imports',
  'hot-cold-inlets': 'Hot and Cold Inlets',
  'html-in-canvas': 'HTML in Canvas',
  'in-app-help': 'Help',
  introduction: 'Introduction',
  'javascript-runner': 'JavaScript',
  'js-integrations': 'JS Integrations',
  'js-modules': 'JS Modules',
  'llm-js': 'LLM API',
  'manage-collections': 'Collections',
  'manage-files': 'Files',
  'manage-presets': 'Presets',
  'manage-saves': 'Saves',
  'message-passing': 'Message Passing',
  'modifying-objects': 'Modifying Objects',
  'network-p2p': 'P2P Messaging',
  'object-settings': 'Object Settings',
  'offline-usage': 'Offline Usage',
  'parameter-automation': 'Parameter Automation',
  'rendering-pipeline': 'Rendering Pipeline',
  'sharing-links': 'Sharing Links',
  shortcuts: 'Shortcuts',
  'supporting-open-source': 'Supporting Open Source',
  'transport-control': 'Transport Control',
  'video-chaining': 'Video Chaining',
  'virtual-filesystem': 'Virtual Filesystem'
};
